# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bush/snickerdoodle_prime/snickerdoodle_prime.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
# IP: The module: 'top_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bush/snickerdoodle_prime/snickerdoodle_prime.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/bush/snickerdoodle_prime/snickerdoodle_prime.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
# IP: The module: 'top_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bush/snickerdoodle_prime/snickerdoodle_prime.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
